import type { Metadata } from "next";
import { mont} from '@/app/ui/font'
import "./globals.css";
import Menu from "./ui/navigation/menu";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mont.variable} antialiased`} id='circularcursor'
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
